### ISSUE TITLE
3 megs worth of uncompressed code jump when included

### ISSUE THREAD

**Issue by hakunin** [tjunghans/react-select#1]
My app (uncompressed) before:

```
        Asset     Size  Chunks             Chunk Names
app-bundle.js  6.66 MB       0  [emitted]  app
    + 882 hidden modules
```

When react-simple-select included:

```
        Asset     Size  Chunks             Chunk Names
app-bundle.js  8.33 MB       0  [emitted]  app
    + 1038 hidden modules
```

This seems weird.

**Comment by tjunghans** [comment]
Hi @hakunin , thanks for pointing that out, will have a look at it.

**Comment by tjunghans** [comment]
Should be fixed now. I had quite a few dev dependencies listed under `dependencies` instead of `devDependencies` in the package.json. I also update react to 15.0.
